services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: journal
      POSTGRES_PASSWORD: journal
      POSTGRES_DB: journal
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

volumes:
  postgres_data:
